### ISSUE TITLE
Error HH8:

### ISSUE THREAD

**Issue by EbubeUd** [Open-Currency-Collective/bxdfi-dsa-contracts#1]
`npm test`

**Expected Behaviour:** 
> Run Tests

**Actual Behaviour:** 
> Error HH8: There's one or more errors in your config file:  
![image_2021-04-18_163225](https://user-images.githubusercontent.com/30143543/115151214-d3c45d00-a063-11eb-920b-eaad625bf494.png)

**Comment by Khay-EMMA** [comment]
You have to be running ganache-cli

**Comment by Khay-EMMA** [comment]
Are you done with the connectors?

**Comment by EbubeUd** [comment]
> You have to be running ganache-cli
I have run the ganache-cli and set up env values but it still displays the same error message

**Comment by EbubeUd** [comment]
> Are you done with the connectors?

Yea, I'm done with the setup. I'll just have to write tests for those connectors

**Comment by EbubeUd** [comment]
Issue was from my env file. Ganache Private Key Variable name was misspelt.
